### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by sepidehhosseinzadeh** [oduwa/Wheat-Count#1]
Can't read the data in Datasets:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    count = PicNumero.run_with_cnn(imagePath)
  File "/home/ec2-user/SageMaker/research/Pic-Numero/PicNumero/PicNumero.py", line 164, in run_with_cnn
    r = CNN.classify(img_data[0], model_file=None,featureRepresentation='glcm', shouldSaveResult=True)
  File "/home/ec2-user/SageMaker/research/Pic-Numero/PicNumero/CNN.py", line 213, in classify
    clf = get_model(model_file)
  File "/home/ec2-user/SageMaker/research/Pic-Numero/PicNumero/CNN.py", line 34, in get_model
    train_data, train_targets, test_data, expected = Helper.unserialize(path+"Datasets/grain_glcm_d1_a4.data")
TypeError: 'NoneType' object is not iterable

**Comment by oduwa** [comment]
Thanks for letting me know about this. I've now fixed the issue but realised that this was written with the most current version of tensorflow in 2016 so you will need tensorflow version r0.7, I think. This is because the newer definitions of **skflow.DNNClassifier()** changed to require the *feature_column* field in the constructor, which is not provided in the project (as it didn't exist when it was written)

**Comment by sepidehhosseinzadeh** [comment]
Thanks for your response. Now I have the following error: 

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    count = PicNumero.run_with_cnn(imagePath)
  File "/home/ec2-user/SageMaker/research/Pic-Numero/PicNumero/PicNumero.py", line 161, in run_with_cnn
    r = CNN.classify(img_data[0], model_file=None,featureRepresentation='glcm', shouldSaveResult=True)
  File "/home/ec2-user/SageMaker/research/Pic-Numero/PicNumero/CNN.py", line 262, in classify
    clf = get_model(model_file)
  File "/home/ec2-user/SageMaker/research/Pic-Numero/PicNumero/CNN.py", line 112, in get_model
    classifier = skflow.DNNClassifier(feature_engineering_fn=conv_model, n_classes=2)
TypeError: __init__() takes at least 3 arguments (3 given)

**Comment by oduwa** [comment]
Yes that's the error i was referring to in my earlier comment about skflow.DNNClassifier(). Are you using the august 2016 version of tensorflow (which i think is r0.7)?
